speech_verbs = {'förklarat', 'upptog', 'säger', 'börjar', 'intygade', 'anmärka',
                'hälsades', 'skrek', 'svara', 'sagt', 'frågat', 'Svara', 'säga',
                'hälsa', 'rättat', 'kommenderade', 'Säg', 'menade', 'svarade',
                'frågade', 'avbröt', 'menar', 'avbrytes', 'inföll', 'säg',
                'fråga', 'upplysa', 'rättade', 'anmärkte', 'röt', 'medgav',
                'predikade', 'började', 'frågan', 'sa', 'frågor', 'sade',
                'fortfor', 'Säger', 'betonade', 'förklarade', 'avbryta',
                'hälsade', 'Sa', 'svarat', 'upplyste', 'ifyllde', 'börjat', 'smålog',
                'trumpetade', 'mumlade', 'sköt', 'klagade', 'fortsatte', 'flämtade'
                'väste', 'föreslog', 'protesterade', 'bekräftade', 'kved', 'uppmanade',
                'erinrade', 'tutade', 'utbrast', 'yttrade', 'ropade', 'ekade', 'pjollrade',
                'invände', 'deklamerade', 'förmanade', 'bestyrkte', 'tog', 'bröt',
                'svarar', 'hälsade', 'tyckte', 'tillrådde', 'brast', 'smågnolade',
                'försäkrade', 'bekände', 'hördes', 'försökte', 'viskade', 'försvarade',
                'kunde', 'klingrade', 'blev', 'harskade', 'förebrådde', 'flämtade',
                'ursäktade', 'väste', 'utropade', 'muckade', 'medlade', 'kompletterade',
                'morrade', 'afbröt', 'hviskade', 'tillade', 'klingade', 'upprepade',
                'spörjer', 'åjade', 'hade', 'tillstod', 'fasade', 'utlät sig med', 
                'avgjorde', 'skrattade'}
